FROM python:3.13-slim
RUN apt-get update && apt-get install -y \
    unixodbc-dev \
    freetds-dev \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/ ./src/

CMD ["python", "-u", "src/migrator.py"]
